### ISSUE TITLE
Cannot reshape a tensor with 64 elements to shape [128,1] (128 elements) for 'loss/Reshape'

### ISSUE THREAD

**Issue by Tesla-jiang** [udel-biotm-lab/BERT-CLRE#1]
Thank you very much for your work. I met a mistake when running the code. Could You help me 

W0322 15:58:36.767313 140542108337984 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 64 elements to shape [128,1] (128 elements) for 'loss/Reshape' (op: 'Reshape') with input shapes: [64,1,1], [2] and with input tensors computed as partial shapes: input[1] = [128,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./BERT/run_re_cp_.py", line 1322, in <module>
    tf.app.run()
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "./BERT/run_re_cp_.py", line 1073, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "./BERT/run_re_cp_.py", line 884, in model_fn
    num_labels, use_one_hot_embeddings)
  File "./BERT/run_re_cp_.py", line 830, in create_model_contrastive_pretraining
    l_pos = tf.reshape(l_pos, (int(FLAGS.train_batch_size/2), 1))
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 131, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 8115, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/miniconda3/envs/TF1.15/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 64 elements to shape [128,1] (128 elements) for 'loss/Reshape' (op: 'Reshape') with input shapes: [64,1,1], [2] and with input tensors computed as partial shapes: input[1] = [128,1].

**Comment by FirstDiscoverer** [comment]
same problem as above

**Comment by FirstDiscoverer** [comment]
got it

train_batch_size=128 can work
